AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RR Product Service - Lambda functions for product parsing

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: production
        LOG_LEVEL: info
        SYNCCENTRIC_HOST: '{{resolve:ssm:/product-service/synccentric/host}}'
        SYNCCENTRIC_AUTH_KEY: '{{resolve:ssm-secure:/product-service/synccentric/auth-key}}'

Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: health.handler
      Events:
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: get
      Tags:
        Service: product-service
        Environment: production

  CreateUrlAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: create-url-analysis.handler
      Events:
        CreateUrlAnalysis:
          Type: Api
          Properties:
            Path: /product-identifiers/urls
            Method: post
      Tags:
        Service: product-service
        Environment: production

  ConvertAsinFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: convert-asin.handler
      Events:
        ConvertAsin:
          Type: Api
          Properties:
            Path: /product-identifiers/asins
            Method: post
      Tags:
        Service: product-service
        Environment: production

  NormalizeCartViewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: normalize-cart-views.handler
      Events:
        NormalizeCartViews:
          Type: Api
          Properties:
            Path: /cart-events/normalize
            Method: post
      Tags:
        Service: product-service
        Environment: production

  NormalizeProductViewsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: normalize-product-views.handler
      Events:
        NormalizeProductViews:
          Type: Api
          Properties:
            Path: /product-events/normalize
            Method: post
      Tags:
        Service: product-service
        Environment: production

Outputs:
  HealthApi:
    Description: API Gateway endpoint URL for Health function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/health/'

  HealthFunction:
    Description: Health Lambda Function ARN
    Value: !GetAtt HealthFunction.Arn

  HealthFunctionIamRole:
    Description: IAM Role created for Health function
    Value: !GetAtt HealthFunctionRole.Arn

  CreateUrlAnalysisApi:
    Description: API Gateway endpoint URL for CreateUrlAnalysis function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/product-identifiers/urls/'

  CreateUrlAnalysisFunction:
    Description: CreateUrlAnalysis Lambda Function ARN
    Value: !GetAtt CreateUrlAnalysisFunction.Arn

  CreateUrlAnalysisFunctionIamRole:
    Description: IAM Role created for CreateUrlAnalysis function
    Value: !GetAtt CreateUrlAnalysisFunctionRole.Arn

  ConvertAsinApi:
    Description: API Gateway endpoint URL for ConvertAsin function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/product-identifiers/asins/'

  ConvertAsinFunction:
    Description: ConvertAsin Lambda Function ARN
    Value: !GetAtt ConvertAsinFunction.Arn

  ConvertAsinFunctionIamRole:
    Description: IAM Role created for ConvertAsin function
    Value: !GetAtt ConvertAsinFunctionRole.Arn

  NormalizeCartViewsApi:
    Description: API Gateway endpoint URL for NormalizeCartViews function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/cart-events/normalize/'

  NormalizeCartViewsFunction:
    Description: NormalizeCartViews Lambda Function ARN
    Value: !GetAtt NormalizeCartViewsFunction.Arn

  NormalizeCartViewsFunctionIamRole:
    Description: IAM Role created for NormalizeCartViews function
    Value: !GetAtt NormalizeCartViewsFunctionRole.Arn

  NormalizeProductViewsApi:
    Description: API Gateway endpoint URL for NormalizeProductViews function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/product-events/normalize/'

  NormalizeProductViewsFunction:
    Description: NormalizeProductViews Lambda Function ARN
    Value: !GetAtt NormalizeProductViewsFunction.Arn

  NormalizeProductViewsFunctionIamRole:
    Description: IAM Role created for NormalizeProductViews function
    Value: !GetAtt NormalizeProductViewsFunctionRole.Arn
