AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: RR Product Service - Lambda functions for product parsing

Globals:
  Function:
    Runtime: nodejs22.x
    Architectures:
      - arm64
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        NODE_ENV: production
        LOG_LEVEL: info

Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Handler: health.handler
      Events:
        Health:
          Type: Api
          Properties:
            Path: /health
            Method: get
      Tags:
        Service: product-service
        Environment: production

Outputs:
  HealthApi:
    Description: API Gateway endpoint URL for Health function
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/health/'

  HealthFunction:
    Description: Health Lambda Function ARN
    Value: !GetAtt HealthFunction.Arn

  HealthFunctionIamRole:
    Description: IAM Role created for Health function
    Value: !GetAtt HealthFunctionRole.Arn
